name: CI
on: push
jobs:
    jest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run tests
              run: |
                  npm ci
                  npm test
    smoke-test-angular:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dir: ['angular9', 'angular10', 'angular11', 'angular12']
        steps:
            - uses: actions/checkout@v2
            - name: Run tests
              run: |
                  npm ci
                  npm run build
                  cd ./smoke-tests/${{matrix.dir}}
                  npm install
                  ./node_modules/.bin/ng generate ngx-cli-toolkit:ng-add
                  cd ./projects/lib1
                  ../../node_modules/.bin/ng generate ngx-cli-toolkit:init
                  ../../node_modules/.bin/ng generate ngx-cli-toolkit:add-schematic --save dependencies
                  ../../node_modules/.bin/ng generate ngx-cli-toolkit:update-schematic update1 --description foo --version 1.2.3
                  ../../node_modules/.bin/ng generate ngx-cli-toolkit:generate-schematic generate1 --description foo
    smoke-test-node:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run tests
              run: |
                  npm ci
                  npm run build
                  cd ./smoke-tests/node
                  npm install
                  ./node_modules/.bin/ng generate ngx-cli-toolkit:ng-add
                  ./node_modules/.bin/ng generate ngx-cli-toolkit:init
                  ./node_modules/.bin/ng generate ngx-cli-toolkit:add-schematic --save dependencies
                  ./node_modules/.bin/ng generate ngx-cli-toolkit:update-schematic update1 --description foo --version 1.2.3
                  ./node_modules/.bin/ng generate ngx-cli-toolkit:generate-schematic generate1 --description foo
